name: Publish ACL package

on:
  push:
    branches:
      - main
    paths:
      - "packages/acl/**"
jobs:
  build:
    uses: ./.github/workflows/package_publisher.yml
    with:
      package_name: acl
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN}}