name: Publish API package

on:
  push:
    branches:
      - main
    paths:
      - "packages/api/**"
jobs:
  build:
    uses: ./.github/workflows/package_publisher.yml
    with:
      package_name: api
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}