name: Publish API package

on:
  push:
    branches:
      - main
    paths:
      - "packages/api/**"
jobs:
  build:
    uses: ./.github/workflows/package_publisher.yml
    with:
      package_name: api
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN}}
