name: Publish Http Errors package for develop

on:
  push:
    branches:
      - develop
    paths:
      - "packages/http-errors/**"
jobs:
  build:
    uses: ./.github/workflows/dev-publisher.yml
    with:
      package_name: http-errors
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN}}