name: Publish Fastify package for develop

on:
  push:
    branches:
      - develop
    paths:
      - "packages/fastify/**"
jobs:
  build:
    uses: ./.github/workflows/dev-publisher.yml
    with:
      package_name: fastify
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN}}