name: Publish Validation package for develop

on:
  push:
    branches:
      - develop
    paths:
      - "packages/validation/**"
jobs:
  build:
    uses: ./.github/workflows/dev-publisher.yml
    with:
      package_name: validation
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN}}