name: Publish Firebase Uploader package for develop

on:
  push:
    branches:
      - develop
    paths:
      - "packages/providers/uploader-firebase/**"
jobs:
  build:
    uses: ./.github/workflows/dev-publisher.yml
    with:
      package_name: providers/uploader-firebase
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN}}