name: Publish fastify package

on:
  push:
    branches:
      - main
    paths:
      - "packages/fastify/**"
jobs:
  build:
    uses: ./.github/workflows/package_publisher.yml
    with:
      package_name: fastify
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}