name: Publish Http-errors Package

on:
  push:
    branches:
      - main
    paths:
      - "packages/http-errors/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: checkout
    - uses: actions/setup-node@v3
      name: Install node.js
      with:
        node-version: "16.x"
        registry-url: 'https://registry.npmjs.org'
    - run: yarn & yarn run bootstrap
      name: Install dependencies
    - run: yarn run build
      name: building package
      working-directory: packages/http-errors
    - run: yarn publish
      name: publishing http-errors
      working-directory: packages/http-errors
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}