name: Publish Http-errors

on:
  push:
    branches:
      - main
    paths:
      - "packages/http-errors/**"
jobs:
  build:    
    uses: ./.github/workflows/package_publisher.yml
    with:
      package_name: http-errors
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN}}