name: Publish uploader-firebase Package

on:
  push:
    branches:
      - main
    paths:
      - 'packages/providers/uploader-firebase/**'
jobs:
  build:
    uses: ./.github/workflows/package_publisher.yml
    with:
      package_name: providers/uploader-firebase
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN}}
      publish_token: ${{ secrets.PUBLISH_TOKEN}}
