name: Publish tinyhttp Package

on:
  push:
    branches:
      - main
    paths:
      - 'packages/tinyhttp/**'
jobs:
  build:
    uses: ./.github/workflows/package_publisher.yml
    with:
      package_name: tinyhttp
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN}}
      publish_token: ${{ secrets.PUBLISH_TOKEN}}
