name: Publish strategy jwt package

on:
  push:
    branches:
      - main
    paths:
      - 'packages/strategies/strategy-jwt/**'
jobs:
  build:
    uses: ./.github/workflows/package_publisher.yml
    with:
      package_name: strategies/strategy-jwt
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN}}
      publish_token: ${{ secrets.PUBLISH_TOKEN}}
