name: Publish sequelize Package

on:
  push:
    branches:
      - main
    paths:
      - "packages/sequelize/**"
jobs:
  build:
    uses: ./.github/workflows/package_publisher.yml
    with:
      package_name: sequelize
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}