name: Publish swagger Package

on:
  push:
    branches:
      - main
    paths:
      - "packages/swagger/**"
jobs:
  build:
    uses: ./.github/workflows/package_publisher.yml
    with:
      package_name: swagger
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}