name: Publish tinyhttp Package

on:
  push:
    branches:
      - main
    paths:
      - "packages/tinyhttp/**"
jobs:
  build:
    uses: ./.github/workflows/package_publisher.yml
    with:
      package_name: tinyhttp
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}