name: Publish uploader Package

on:
  push:
    branches:
      - main
    paths:
      - 'packages/uploader/**'
jobs:
  build:
    uses: ./.github/workflows/package_publisher.yml
    with:
      package_name: uploader
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN}}
